#!/bin/sh
### BEGIN INIT INFO
# Provides:		alexatv
# Required-Start:	$all
# Required-Stop:	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start alexatv at boot time
# Description:		Enable service provided by alexatv.
### END INIT INFO

dir="/usr/local/bin"
cmd="python alexatv.py /usr/local/etc/alexatv/alexatv.cfg"


name=`basename $0`
pid_file="/var/run/$name.pid"
log="/var/log/$name.log"


get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        sudo $cmd >> "$log" 2>&1 &
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        sleep 1
        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|status}"
    exit 1
    ;;
esac

exit 0

